export const SET_CARD_NUMBER = "SET_CARD_NUMBER";
export const SET_CARD_MONTH = "SET_CARD_MONTH";
export const SET_CARD_YEAR = "SET_CARD_YEAR";
export const SET_CARD_OWNER_NAME = "SET_CARD_OWNER_NAME";
export const SET_CARD_OWNER_SURNAME = "SET_CARD_NUM";